# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 evroc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-api-provider-evroc.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api-provider-evroc.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "cluster-api-provider-evroc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cluster-api-provider-evroc.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cluster-api-provider-evroc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.securityContext | nindent 8 }}
      containers:
      - name: manager
        image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        args:
        {{- if .Values.controller.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        - --health-probe-bind-address=:8081
        {{- if .Values.webhook.enabled }}
        - --webhook-port={{ .Values.webhook.port }}
        - --webhook-cert-dir={{ .Values.webhook.certDir }}
        {{- end }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.logging.level | quote }}
        - name: LOG_FORMAT
          value: {{ .Values.logging.format | quote }}
        {{- if .Values.debug }}
        - name: DEBUG
          value: "true"
        {{- end }}
        {{- with .Values.controller.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 8081
          name: healthz
          protocol: TCP
        {{- if .Values.webhook.enabled }}
        - containerPort: {{ .Values.webhook.port }}
          name: webhook-server
          protocol: TCP
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - containerPort: {{ .Values.metrics.port }}
          name: metrics
          protocol: TCP
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.controller.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controller.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.controller.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/evroc
          readOnly: true
        {{- if .Values.webhook.enabled }}
        - mountPath: {{ .Values.webhook.certDir }}
          name: cert
          readOnly: true
        {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        secret:
          secretName: {{ include "cluster-api-provider-evroc.configSecretName" . }}
      {{- if .Values.webhook.enabled }}
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ include "cluster-api-provider-evroc.fullname" . }}-webhook-server-cert
      {{- end }}
