# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 evroc

{{ if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "cluster-api-provider-evroc.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "cluster-api-provider-evroc.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "cluster-api-provider-evroc.fullname" . }}-serving-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cluster-api-provider-evroc.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-evroccluster
  failurePolicy: Fail
  name: vevroccluster.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - evrocclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "cluster-api-provider-evroc.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-evrocmachine
  failurePolicy: Fail
  name: vevrocmachine.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - evrocmachines
  sideEffects: None
{{ end }}
