# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 evroc

---
# This configuration is for teaching kustomize how to update name ref substitution
nameReference:
- kind: Issuer
  group: cert-manager.io
  fieldSpecs:
  - kind: Certificate
    group: cert-manager.io
    path: spec/issuerRef/name

namespace:
- kind: Issuer
  group: cert-manager.io
  path: metadata/name
  create: true
- kind: Certificate
  group: cert-manager.io
  path: metadata/name
  create: true

varReference:
- path: metadata/annotations/cert-manager.io\/inject-ca-from
  kind: MutatingWebhookConfiguration
- path: metadata/annotations/cert-manager.io\/inject-ca-from
  kind: ValidatingWebhookConfiguration
